version: "3.7"

services:
  zookeeper-server:
    image: juanmartinez/zookeeper:3.4.14
    container_name: zookeeper-server
    hostname: zookeeper-server
    env_file:
    - zookeeper.env
  kafka-broker:
    image: juanmartinez/kafka:2.5.0
    container_name: kafka-broker
    hostname: kafka-broker
    env_file:
    - kafka.env
  cmak:
    image: juanmartinez/cluster:2.0.0.2
    container_name: cmak
    hostname: cmak
    ports:
    - "9000:9000"
    env_file:
    - cmak.env

  hoster:
    image: juanmartinez/docker-hoster
    container_name: hadoop_hoster
    hostname: hadoop_hoster
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/hosts:/tmp/hosts
